version: '3.8'

services:
  master:
    build:
      context: ./master
    ports:
      - 8088:8088


  worker:
      build:
        context: ./worker
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - worker
    ports:
      - "4000:4000"